### ISSUE TITLE
Clicking the home button on the end of year page goes to the bootstrap starter template.

### ISSUE THREAD

**Issue by willbarkoff** [CoursesPlus/coursesplus.github.io#11]
Can you please fix it @thatoddmailbox. I cannot because it is housed on your server.

**Comment by thatoddmailbox** [comment]
Ack, sorry. Do you think it should go to the coursesplus.tk page or to the "put in your email here" page?

**Comment by willbarkoff** [comment]
Put your email in here.
**Sorry about that. It is my mistake.**

**Comment by thatoddmailbox** [comment]
Done!

(also, it's my fault; I didn't let you access the server)
