### ISSUE TITLE
Font Awesome List Not Showing Up

### ISSUE THREAD

**Issue by willbarkoff** [CoursesPlus/coursesplus.github.io#2]
Font Awesome List Not Showing Up (Under Full List of Features)

**Comment by medensqui** [comment]
SUCKS FOR YOU

I haven't edited all the features yet

**Comment by thatoddmailbox** [comment]
That's because `fa-list-o` isn't an icon. But `fa-list` is! I'm having Josh commit that because he is already editing the index file.
