### ISSUE TITLE
License for feature image 2

### ISSUE THREAD

**Issue by thatoddmailbox** [CoursesPlus/coursesplus.github.io#4]
@nywillb Do you have a link to the page where you got the cloud image? (or at least license info, so we know we can use it)

**Comment by willbarkoff** [comment]
It's license is Creative Commons Attribution-Share Alike 3.0 Unported. The URL is: http://commons.wikimedia.org/wiki/File:Appearance_of_sky_for_weather_forecast,_Dhaka,_Bangladesh.JPG

**Comment by thatoddmailbox** [comment]
OK, thanks. However, this means we have to link to the source. "Creative Commons **Attribution**-Share Alike 3.0 Unported". Re-opening this for now.

**Comment by willbarkoff** [comment]
Oh. I did not realize.

**Comment by thatoddmailbox** [comment]
It's fine; I fixed it for you.

**Comment by willbarkoff** [comment]
Thanks :smile:

**Comment by willbarkoff** [comment]
What is Jekyll?

**Comment by thatoddmailbox** [comment]
Templating system. It is the only templating system GitHub Pages currently supports. The page layout is in the _layouts folder, while markdown files in different directories have the content. GitHub Pages then creates HTML from the markdown, joins that with the template, and shows those files. See the commit comment for the directories, or wait for me to get off of mobile to explain more.
