### ISSUE TITLE
Links to old versions

### ISSUE THREAD

**Issue by thatoddmailbox** [CoursesPlus/coursesplus.github.io#6]
The current CoursesPlus website has links to download old versions of CoursesPlus (at least, old version until the switch to the webstore). This website doesn't.

Actually, do you even think we have to link to those?

**Comment by medensqui** [comment]
Um...Will anyone want them?

**Comment by willbarkoff** [comment]
No. They cannot even be installed.

**Comment by thatoddmailbox** [comment]
They can be, but I don't know if anyone wants them. Perhaps they do.
